version: '3'

services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: dev_db

  db_test:
    image: postgres:13.3-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
  
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: "postgres://dev_user:dev_pass@db:5432/dev_db?schema=public"

  migration:
    build: .
    command: npm run migrate:generate
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://dev_user:dev_pass@db:5432/dev_db?schema=public"